# Generated by Django 6.0.3 on 2026-03-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Strength", "Strength"),
                            ("Cardio", "Cardio"),
                            ("Flexibility", "Flexibility"),
                            ("Balance", "Balance"),
                            ("HIIT", "HIIT"),
                        ],
                        default="Strength",
                        max_length=20,
                    ),
                ),
                (
                    "muscle_group",
                    models.CharField(
                        choices=[
                            ("Chest", "Chest"),
                            ("Back", "Back"),
                            ("Shoulders", "Shoulders"),
                            ("Biceps", "Biceps"),
                            ("Triceps", "Triceps"),
                            ("Forearms", "Forearms"),
                            ("Core", "Core"),
                            ("Quads", "Quads"),
                            ("Hamstrings", "Hamstrings"),
                            ("Glutes", "Glutes"),
                            ("Calves", "Calves"),
                        ],
                        default="Chest",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
